Default: &defaults
  database: asblballondoxygene.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: asblballondoxygene_test.sqlite3
  <<: *defaults

Staging:
  database: asblballondoxygene_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: asblballondoxygene_production.sqlite3
  poolsize: 100
  <<: *defaults
